# Generated by Django 4.2 on 2024-06-29 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problemName', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150)),
                ('submissionId', models.IntegerField(unique=True)),
                ('lang', models.CharField(max_length=100)),
                ('duringContest', models.CharField(max_length=3)),
                ('srcLink', models.URLField(max_length=2000)),
            ],
        ),
    ]
